using System.IO;
using UnityEditor;
using UnityEngine;
using UnityProjectPostProcessor;

#if UNITY_EDITOR_WIN

/// <summary>
/// Add all reference projects in your model project to the .csproj generated by Unity VS.
/// </summary>
/// <remarks>
/// Visual Studio Tools for Unity 必須。
/// </remarks>
[InitializeOnLoad]
public class VSProjectPostprocessor
{
    /// <summary>
    /// Game.csproj を追加する。
    /// </summary>
    private static readonly ProjectPostprocessor ProjectPostprocessor = new ProjectPostprocessor(new CSharpProject(@"..\[path to your model project].csproj"));

    static VSProjectPostprocessor()
    {
        ProjectPostprocessor.Generate();
    }

    [MenuItem("Visual Studio Tools/Generate Project Files with project references")]
    private static void Generate()
    {
        ProjectPostprocessor.Generate();
    }
}

#endif
